spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_data?serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  cache:
#    redis:
#      time-to-live: 30s
#      use-key-prefix: true
#      key-prefix: boot_

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
logging:
  level:
    com:
      example:
        cache:
          mapper:
            UserMapper: debug
