spring:
  application:
    name: server-push
  boot:
    admin:
      client:
        url: http://localhost:8989
#        instance:
#          prefer-ip:
server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always