management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  profiles:
    active: dev

  boot:
    admin:
      client:
        url: http://localhost:8989
  application:
    name: actuator-application
