spring:
  mail:
    host: smtp.qq.com
    username: 1952932103@qq.com
    password: blwgkvxdzefcddge
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
    default-encoding: UTF-8
    port: 465
