server:
  port: 9090

web:
  upload-path: C:\Users\lenovo\Desktop\upload\

spring:
  web:
    resources:
      static-locations: classpath:/static/,file:${web.upload-path}
  servlet:
    multipart:
      max-file-size: 1048576000
      max-request-size: 1048576000

minio:
  endPoint: http://43.137.12.232:9000
  accessKey: admin
  secretKey: 12345678